<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
<TITLE>University of Surrey, Physics: Essential Mathematics</TITLE>
<link rel="STYLESHEET" type="text/css" href="styles.css">
<link rel="stylesheet" href="prism.css" data-noprefix />

<meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">
</HEAD>
<body>

<script language="JavaScript" src="menubar.js" type="text/javascript"></script>

<div align="center"><h1>1EM - Essential Mathematics / Computational Laboratory</h1></div>
<div>
<h2>Unit 10: Debugging:  Development of techniques to fix coding problems</h2>

<h3>Introduction</h3>

<p>While it would be nice if every program you write works first time, this is rarely the case.  Planning the structure in advance can help write better code, but being able to fix non-working problems, or &quot;debugging&quot; is a useful skill to develop.  This unit introduces some methods of debugging. </p>

<p>Let's get one thing clear first : Debugging is unavoidable. No
matter how good at coding you are, you will always have to spend
considerable amount of time debugging codes. This being said, there
are ways to help you in debugging and solving the problems you will
encounter.</p>

<hr>

<h3>Interpreter messages</h3>

<p>In the previous units, you inevitably have had errors from Python
directly. These errors are usually looking like :</p>

<pre>ZeroDivisionError: float division by zero</pre>

<p>or</p>

<pre>NameError: name 'a' is not defined</pre>

<p>or </p>

<pre>IndexError: list index out of range</pre>

<p>We call these errors <strong>interpreter</strong> errors. These are generally easy to debug, since the interpreter is giving you all the information you need. Let's break down one of these errors in an example. Start by copying the following code in a file called <code>error.py</code> :</p>

<pre><code>def print_values(l, N):
    for i in range(N):
        print(l[i])

a = int(input('Enter a positive integer : '))

my_list = [1, 2, 3, 4, 5, 6]
print_values(my_list, a)</code></pre>

<p>Now let's try to run the code and enter the value <code>10</code> :</p>

<pre>Enter a positive integer : 10
1
2
3
4
5
6
Traceback (most recent call last):
  File "error.py", line 8, in &lt;module&gt;
    print_values(my_list, a)
  File "error.py", line 3, in print_values
    print(l[i])
    IndexError: list index out of range</pre>

<p>The error message is made of two parts : the stacktrace and the exception.</p>

<p>The <strong>stacktrace</strong> is a list of "places" in the code where the error was generated. To understand this, let's take a look at the example. First it indicates that the error is in a file called <code>error.py</code>, at line 8. This line corresponds to the line where we call the function <code>print_values</code>. Then, the stacktrace continues since the error has been sent from inside the function. Finally, the stacktrace tells us that the error is on line 3 (in the same file), in the function <code>print_values</code>. The line generating the error is : <code>print(l[i])</code>. By reading the stacktrace, you can find precisely <strong>where</strong> the error occurs. But you won't know why until you read the following line !</p>

<p>The <strong>exception</strong> description tells you what type of error. Here, we see that the error is of type <code>IndexError</code>, and in plain english : "list index out of range". The error tells us that we are accessing a list (<code>l</code>), and trying to get an index (<code>i</code>) that is out of the boundaries of the list. Indeed, <code>print_values</code> is being called on <code>my_list</code> that has only 6 elements, and we are iterating on <code>i</code> between 0 and 9 included. So as soon as <code>i==6</code>, we try to access a value that is not defined and the program crashes !</p>

<p>By reading the stack trace and the exception, you can find why and where your program crashed. That is a very useful part of debugging.</p>

<hr>

<h3>Handling exceptions</h3>

<p>From the example we have just seen, we know that as soon as our
program goes over an index of 5, it will crash since the list has only
6 elements. Of course this is an error we could easily fix by
forbidding the user to enter an invalid value. But for the sake of
ther argument, let's imagine we cannot fix things this way.</p>

<p>Python has a very useful mechanism to handle exceptions when they occur : <code>try</code>/<code>except</code>. The <code>try</code> command starts a new block of code in which exceptions can be <code>caught</code>. That means that if an exception happens in this block of code you can execute another block of code instead of having the program crash. This extra block of code will be defined in an <code>except</code> block right after the <code>try</code> block. Considering the following modification of our <code>print_values</code> function :</p>

<pre><code>def print_values(l, N):
    try:
        for i in range(N):
            print(l[i])
    except:
        print('Oops ! A problem has been detected !')</code></pre>

<p>Trying to execute the code now will not crash anymore. Instead the code will tell you that an error has been detected as planned.</p>

<p>The <code>try/except</code> instructions are very powerful and give you a better control over your programs. But it should not be used as a way to avoid dealing with problems. Instead they should be used in two ways :</p>

<ol>
  <li>To catch an exception that you know is going to happen, and deal with it because your code should be dealing with it under normal usage.</li>
  <li>As a temporary measure to understand in more details why the code is failing.</li>
</ol>

<hr>
<h3>Multiple exceptions</h3>

<p>The <code>except</code> instruction can be used to catch different
types of exceptions. The default behaviour (as we have used above)
catches any exception and executes what is inside
the <code>except</code> block. But consider the following code :</p>

<pre><code>my_list = [1, 2, 3, 4, 5, 6]

index = int(input('Enter a positive integer : '))
value = float(input('Enter a value : '))

print(my_list[index] / value)</code></pre>

<p>In this code, two things could go wrong : First, the user could enter an invalid index that would lead to an <code>IndexError</code> as before; but also, the user could enter <code>0.0</code> as a value, which would lead to a <code>ZeroDivisionError</code>. We might want to handle the two exceptions differently. In this case, we can catch specific exceptions using the <code>except</code> instruction :</p>

<pre><code>my_list = [1, 2, 3, 4, 5, 6]

index = int(input('Enter a positive integer : '))
value = float(input('Enter a value : '))

try:
    print(my_list[index] / value)
except IndexError:
    print('The index provided is not valid ! index = ', index)
except ZeroDivisionError:
    print('Cannot divide by 0.0 !')</code></pre>

<p>If you have a doubt about the name of the exception you are try to catch, take a look at the error message you get. The most common exceptions and their meaning is regrouped in the following table : </p>

<p class="indexlink">
  <table>
    <tr>
      <td><strong>Exception</strong></td>
      <td><strong>Meaning</strong></td>
      <td><strong>Example</strong></td>
    </tr>
    
    <tr>
      <td><code>AttributeError</code></td>
      <td>Trying to use an attribute that does not exist</td>
      <td><pre><code>a = [1, 2, 3, 4]
a.imaginary_attribute = 12</code></pre></td>
    </tr>

    <tr>
      <td><code>ImportError</code></td>
      <td>Importing a non-existing module</td>
      <td><pre><code>import a_module_that_does_not_exist</code></pre></td>
    </tr>

    <tr>
      <td><code>IndexError</code></td>
      <td>Accessing a list or tuple outside of its bounds</td>
      <td><pre><code>a = [1, 2, 3]
b = ('a', 'b', 'c')
print(a[6], b[12])</code></pre></td>	    
    </tr>

    <tr>
      <td><code>KeyError</code></td>
      <td>Access a dictionary with a key that does not exist</td>
      <td><pre><code>d = {'a':10, 'b':12}
print(d['c'])</code></pre></td>
    </tr>

    <tr>
      <td><code>NameError</code></td>
      <td>Using a variable that has not been declared before</td>
      <td><pre><code>a = non_declared_variable</code></pre></td>
    </tr>

    <tr>
      <td><code>RecursionError</code></td>
      <td>Recursive function has been called too many times</td>
      <td><pre><code>def recursive(x):
    recursive(x)

recursive(10)</code></pre></td>
    </tr>

    <tr>
      <td><code>TypeError</code></td>
      <td>Using an invalid type for an operation</td>
      <td><pre><code>a = 10 + 'abc'</code></pre></td>
    </tr>

    <tr>
      <td><code>ValueError</code></td>
      <td>Using an inappropriate value for a function</td>
      <td><pre><code>from math import sqrt
print(sqrt(-5.0))</code></pre></td>
    </tr>

    <tr>
      <td><code>ZeroDivisionError</code></td>
      <td>Dividing by zero</td>
      <td><pre><code>print(1.0 / 0.0)</code></pre></td>
    </tr>
  </table>
</p>

<p>This list is non exhaustive (there are other Exceptions). If you
want the complete list of native exceptions in Python, follow
this <a href="https://docs.python.org/3/library/exceptions.html#Exception">link</a></p>

<hr>

<h3>Other debugging</h3>

<p>Exception handling should cover part of your bugs. Unfortunately,
these bugs are the easiest to find : the one where the program
crashes. There is another class of bugs, unfortunately more frequent
and a lot more annoying : wrong results.</p>

<p>When your program is running perfectly but not giving the right
answer, that is when trouble starts, because there is no easy way to
debug this. To avoid as much as possible wrong results or to get out
of such an error as quickly as possible, here are a few rules to
respect :</p>

<ul>
  <li><strong>Name your variables explicitly</strong> : Each variable
  should have a proper name and your code should have as much
  semantics as possible. By semantics, we mean that your code should
  be written in a way to be as clear as possible over its intentions :
  what are we computing, when, how and why.</li>
  <li><strong>Study the limit cases</strong>.This was covered in the
  previous unit : always try to determine which are the cases that
  might be poorly managed by the algorithms you are using</li>
  <li><strong>Print, print and more printing</strong>. In these cases,
  printing is your best friend. You should track the evolution of the
  main variables of your program so that you make sure that everything
  evolves as you want it to !</li>
  <li><strong>More semantics</strong>. You should factor as much code
  as possible in functions. These functions should represent semantic
  units that you use in your code making everything clear for you and
  the other developers that might read the code</li>
  <li><strong>Unit testing</strong>. Unit testing is a very simple yet
  very efficient way to make sure your code is flawless. As soon as
  your code is well segmented and divided in functions, make sure to
  test each of these functions outside of your program. Each single
  functionality of your code should come with an extensive list of
  tests to make sure that everything works accordingly to plan. By
  doing this, you make sure that every single brick that constitutes
  your program is sane and well-behaved. You can read more about unit
  tests in
  Python <a href="https://docs.python.org/3.5/library/unittest.html">here</a>
  for the python module
  and <a href="https://docs.python-guide.org/writing/tests/">here</a>
  for a tutorial on how to use these modules for your own code.</li>
</ul>

<p>One last thing : debugging takes time and experience. So the more
you code, the easier debugging will be.</p>

<div>Now move on to <a href="exercise10.html">Exercise 10</a>, where
you can test some of these techniques.</div>

</div>
</BODY>
<!-- Syntax highlighting -->
<script language="JavaScript" src="prism.js" type="text/javascript"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>
  $('code').addClass('language-python');
</script>
</HTML>
